### ISSUE TITLE
Unable to find 'app\assets\AppAsset'

### ISSUE THREAD

**Issue by RusNimex** [yii2mod/yii2-ion-slider#1]
Ошибка при попытке IonSliderAsset::register($view);

```
Unknown Class – yii\base\UnknownClassException

Unable to find 'app\assets\AppAsset' in file: /home/bitrix/www/frontend/assets/AppAsset.php. Namespace missing?
```

Возможно, нужно убрать зависимость app\assets\AppAsset...

**Comment by ihorchepurnyi** [comment]
fixed

**Comment by Jen-Persly** [comment]
How?

**Comment by ihorchepurnyi** [comment]
Hi, I replaced AppAsset to YiiAsset on this [line](https://github.com/yii2mod/yii2-ion-slider/blob/master/IonSliderAsset.php#L37)
