### ISSUE TITLE
Put back "type" in the $pluginOptions property

### ISSUE THREAD

**Issue by machour** [yii2mod/yii2-ion-slider#4]
Hi,

I think that the "type" options should go back inside the $pluginOptions, as it is confusing for developers.

BC could be maintained by checking if type was provided as a direct property and using it, but if provided $pluginOptions['type'] should be considered valid.

**Comment by ihorchepurnyi** [comment]
Hi, I have updated the IonSlider.php. Now, `type` of the slider taken from pluginOptions array.
