### ISSUE TITLE
...does not exist: ...vendor/bower/ion.rangeSlider

### ISSUE THREAD

**Issue by aleksanderd** [yii2mod/yii2-ion-slider#5]
Hi!

After some updates I got `The file or directory to be published does not exist: /<projectDir>/vendor/bower/ion.rangeSlider`

I just updated my project to latest fxp/etc (I don't sure what concrete made the fail) and the directory named in lower case (ion.rangeslider). 

For now I just created a symlink(ion.rangeslider => ion.rangeSlider) to solve the problem. But may be there is a more correct way to fix it? May be [here](https://github.com/yii2mod/yii2-ion-slider/blob/master/IonSliderAsset.php#L17) ?

thnx

**Comment by ihorchepurnyi** [comment]
Hi, to change the path to bower folder for this plugin, you can configure the assetManager array in your application configuration: 

``` php
'assetManager' => [
            'bundles' => [
                'yii2mod\slider\IonSliderAsset' => [
                    'sourcePath' => '@bower/ion.rangeslider'
                ],
            ]
        ],
```
