### ISSUE TITLE
change the slider skin is not working

### ISSUE THREAD

**Issue by gitrequests** [yii2mod/yii2-ion-slider#8]
I configure my assetmanager bundles, but asset manager load wrong css:
css/ion.rangeSlider.skinNice.css

For experiment i delete all css and js from IonSliderAsset, but scripts and styles STILL LOADING!

Check, please!

**Comment by ihorchepurnyi** [comment]
The following configuration works for me
```php
'assetManager' => [
            'bundles' => [
                'yii2mod\slider\IonSliderAsset' => [
                    'css' => [
                        'css/normalize.css',
                        'css/ion.rangeSlider.css',
                        'css/ion.rangeSlider.skinNice.css'
                    ]
                ],
            ],
        ],
```
http://awesomescreenshot.com/0356cj3m70

I tested on Yii 2.0.12 (advanced template), php 7.1, fxp/composer-asset-plugin:~1.3.1, `dev-master` version of this package

**Comment by gitrequests** [comment]
Just for test, change css/ion.rangeSlider.skinHTML5.css

**Comment by ihorchepurnyi** [comment]
Configuration
```php
'yii2mod\slider\IonSliderAsset' => [
                    'css' => [
                        'css/normalize.css',
                        'css/ion.rangeSlider.css',
                        'css/ion.rangeSlider.skinHTML5.css'
                    ],
                ],
```
Result - http://awesomescreenshot.com/06e6cj3u30
